import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchCafes } from "../lib/cafes";
import useTrackLocation from "../hooks/use-track-location";
import { useEffect, useContext, useState } from "react";
import { ACTION_TYPES, CafeContext } from "../store/cafe-Context";

export async function getStaticProps() {
    const cafes = await fetchCafes();
    return {
        props: { cafes },
    };
}

export default function Home(props) {
    const [cafesError, setCafesError] = useState("");

    const { dispatch, state } = useContext(CafeContext);

    const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
        useTrackLocation();

    const { cafes, latLong } = state;

    useEffect(async () => {
        if (latLong) {
            try {
                const fetchCafes = await fetch(
                    `api/getCafesByLocation?${latLong}&limit=30`
                );
                const cafes = await fetchCafes.json();

                dispatch({
                    type: ACTION_TYPES.SET_CAFES,
                    payload: { cafes },
                });
                setCafesError("");
            } catch (error) {
                setCafesError(error.message);
            }
        }
    }, [latLong]);

    const handleOnBannerButtonClick = () => {
        handleTrackLocation();
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Cafe Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Banner
                    buttonText={
                        isFindingLocation ? "Locating..." : "View Cafes Nearby!"
                    }
                    handleOnClick={handleOnBannerButtonClick}
                />
                {locationErrorMsg && (
                    <p>Something went wrong: {locationErrorMsg}</p>
                )}
                {cafesError && <p>Something went wrong: {cafesError}</p>}
                <div className={styles.heroImage}>
                    <Image
                        src="/static/hero-image.png"
                        width={700}
                        height={400}
                    />
                </div>

                {cafes.length > 0 && (
                    <div className={styles.sectionWrapper}>
                        <h2 className={styles.heading2}>Cafes Near Me</h2>
                        <div className={styles.cardLayout}>
                            {cafes.map((cafe) => {
                                return (
                                    <Card
                                        key={cafe.id}
                                        className={styles.card}
                                        name={cafe.name}
                                        imgUrl={cafe.imgUrl}
                                        href={`/cafe/${cafe.id}`}
                                    />
                                );
                            })}
                        </div>
                    </div>
                )}

                {props.cafes.length > 0 && (
                    <div className={styles.sectionWrapper}>
                        <h2 className={styles.heading2}>Dudweiler Cafes</h2>
                        <div className={styles.cardLayout}>
                            {props.cafes.map((cafe) => {
                                return (
                                    <Card
                                        key={cafe.id}
                                        className={styles.card}
                                        name={cafe.name}
                                        imgUrl={cafe.imgUrl}
                                        href={`/cafe/${cafe.id}`}
                                    />
                                );
                            })}
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
}
